### ISSUE TITLE
こんにちは。

### ISSUE THREAD

**Issue by koumaza** [IdeaMapWeb/themechanges-todolist-project#1]
@IdeaMapWeb さん、
こんにちは、N高の方ですか？ よろしくお願いします。
私は元N中生でいま中学3年です。

`github.io`ですが、これはGitHub Pro ユーザーにしか使えません。
ですが学生なら、https://education.github.com/pack を使って無償でProになったり他の有料サービスを無料に使えたりしますよ。

**Comment by mrstash101** [comment]
Thx for your comment
